name: 'AzureSignTool'
description: 'An action that calls: https://github.com/fluffy-bunny/AzureSignTool'
author: 'Fluffy Bunny'

branding:
  icon: 'file'  
  color: 'yellow'
  
inputs:
  azure_sign_tool_credentials:              
    description: 'If using client_credentials, please pull this from secrets.  If using Managed Identity then this can be in the clear'
    default: ''

  azure_sign_tool_assembly:              
    description: 'Path to the AzureSignTool.dll. i.e. ./tools/AzureSignTool-DEV/netcoreapp2.1/any/AzureSignTool.dll'
    default: ''

  files_to_sign:              
    description: 'Path to the <files_to_sign.txt>. i.e. files/files-to-sign.txt'
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
