name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  repository_dispatch:
    types: 
      [my-event]
env:
  AZURE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.201'              # set this to the dotnet version to use

jobs:
  myEvent:
    runs-on: windows-latest
    steps:
      - name: my-event step 1
        shell: pwsh
        run:  |
          pushd './${{ env.AZURE_PATH }}'
          $a = ($pwd).path
          echo "a:"$a
          popd

  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run build 
        npm run pack
    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: dist

  test: # make sure the action works on a clean machine without building
    needs: build
    runs-on: windows-latest
    steps:
    
    - name: 'az login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Action Checkout
      uses: actions/checkout@v1

    - name: download-artifact from build
      uses: actions/download-artifact@v1
      with:
        name: my-artifact
        path: dist

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Simulate Buid via Copy
      shell: bash
      run: |
        cp -r ./files ./builtFiles

    - name: Recursive File Query by Extension
      uses: fluffy-bunny/action-filequery@v0.2dev
      with: 
        folder: builtFiles
        outputFile: 'builtFiles/files-to-sign.txt'

    - name: This Action
      uses: ./
      with: 
        azure_sign_tool_credentials: ${{ secrets.AZURE_SIGN_TOOL_CREDENTIALS_MANAGED_IDENTITY }}
        azure_sign_tool_assembly: ./tools/AzureSignTool-DEV/netcoreapp2.1/any/AzureSignTool.dll
        files_to_sign: builtFiles/files-to-sign.txt

    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: signed-files
        path: builtFiles

    - name: Add Dist Files to source control
      run: |
        git add dist/\\*    
    
    - name: Commit files
      shell: bash
      run: |
        counter=0
        FILES=$(git diff --name-only)
        for FILE in $FILES
        do
            counter=$(( $counter + 1 ))
            echo "$counter:$FILE"
        done

        if [[ $counter -gt 0 ]]; then
          echo "$counter files being commited...."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          echo "::set-output name=commitSucess::true"
        else
          echo "Nothing to commit...."
          echo "::set-output name=commitSucess::false"
        fi


    - name: Push changes
      uses: ad-m/github-push-action@master
      if: ${{ steps.step_one.outputs.commitSucess }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 


         
