name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
env:
  AZURE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.102'              # set this to the dotnet version to use

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run build 
        npm run pack
    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: dist

  test: # make sure the action works on a clean machine without building
    needs: build
    runs-on: windows-latest
    steps:
    
    - name: 'az login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Action Checkout
      uses: actions/checkout@v1

    - name: download-artifact from build
      uses: actions/download-artifact@v1
      with:
        name: my-artifact
        path: dist

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Recursive File Query by Extension
      uses: ghstahl/github-action-filequery@v0.1dev
      with: 
        milliseconds: 1000
        folder: files
        outputFile: 'files/files-to-sign.txt'
    - name: This Action
      uses: ./
      with: 
        milliseconds: 1000
        folder: 'files'
        recursive: true
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        azure_sign_tool_credentials: ${{ secrets.AZURE_SIGN_TOOL_CREDENTIALS }}
        azure_sign_tool_assembly: ./tools/AzureSignTool/netcoreapp2.1/any/AzureSignTool.dll

    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: signed-files
        path: files

    - name: 'Install AzureSignTool'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_PATH }}'
        $a = ($pwd).path
        echo "a:"$a
        popd


         